image: docker:latest
services:
  - docker:dind
stages:
  - build

build:
  before_script:
    - docker info
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_REF_SHA
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGAE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-build/

include:
  - template: Container-Scanning.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml