image: docker:latest
services:
  - docker:dind
stages:
  - build

build:
  before_script:
    - docker info
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/fronbasal/tikbot .
    - docker push registry.gitlab.com/fronbasal/tikbot
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-build/

